apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: server-info-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vaiz1982/k8s_practice_Server-info.git         ##add hre ! 
    targetRevision: main
    path: server-info/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
