apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
configMapGenerator:
  - name: server-info-config
    literals:
      - APP_NAME=server-info
      - APP_VERSION=1.0.0
      - APP_ENV=production
labels:
  - pairs:
      app: server-info
    includeSelectors: true              ##silents 
