apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

configMapGenerator:
  - name: server-info-config
    behavior: merge
    literals:
      - APP_ENV=production

patches:
  - target:
      kind: Deployment
      name: server-info
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: server-info
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: server-info.local
